# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Isolated Nexus
email: 
description: > # this means to ignore newlines until "baseurl:"
  This website serves as my potpurri of experiences and learnings of an Electronics undergraduate.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: akhilrbaranwal
github_username:  akhilrb
facebook_username: akhil.r.baranwal
linkedin_username: akhil-raj-baranwal
quora_userame: Akhil-Raj-Baranwal
telegram_username: akhilrb
disqus:
  shortname: "akhilrb"

#Google-Analytics
google_analytics: UA-102675565-1

header_pages:
  - blog.md
  - nerdstuff.md
  - exploitingAnArduino.md
  - zabout.md

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
